### PR TITLE
Update LINGUAS

### PR DESCRIPTION
**Pull request by safak45x**
tr.po add pls

### CODE REVIEW

**Comment by z0o0p** [comment]
@safak45x, I am not completely sure what you have done. You have added Turkish to the LINGUAS file and not included any actual translations.

If you want Turkish translations for the application, please open an issue so that somebody can work on it.

**Comment by safak45x** [comment]
[tr.po.zip](https://github.com/z0o0p/alohomora/files/5287138/tr.po.zip)
if you add
all files are translated

**Comment by z0o0p** [comment]
@safak45x, there are recent changes in the application. Do you mind updating your translations to match the current application? Also, you seem to have missed out on the extra folder.

Your contributions are highly appreciated. Please commit your changes instead of externally attaching it here. Thank you :)

**Comment by safak45x** [comment]
> @safak45x, there are recent changes in the application. Do you mind updating your translations to match the current application? Also, you seem to have missed out on the extra folder.
> 
> Your contributions are highly appreciated. Please commit your changes instead of externally attaching it here. Thank you :)

Github don't understand much, sorry
So I'm sending the files to you
Please be forgiven for my mistake

**Comment by safak45x** [comment]
I'm a newbie to these jobs just trying to contribute

**Comment by safak45x** [comment]
po/tr.po

**Comment by safak45x** [comment]
> @ safak45x , uygulamada son değişiklikler var. Çevirilerinizi mevcut uygulamaya uyacak şekilde güncellemenin bir sakıncası var mı? Ayrıca, ekstra klasörü kaçırmış görünüyorsunuz.
> 
> Katkılarınız çok takdir ediliyor. Lütfen değişikliklerinizi buraya harici olarak eklemek yerine uygulayın. Teşekkür ederim :)

If the file is opened, I will make the necessary edits again.

**Comment by z0o0p** [comment]
@safak45x, everyone starts somewhere and your contribution is highly appreciated.

For now, I will commit your translations myself. Whenever you feel you have a grasp over GitHub and its working, you can update your translations. Is that okay?

**Comment by safak45x** [comment]
> @ safak45x , herkes bir yerden başlar ve katkınız çok takdir edilmektedir.
> 
> Şimdilik çevirilerinizi kendim yapacağım. GitHub'ı ve çalışmasını anladığınızı hissettiğinizde çevirilerinizi güncelleyebilirsiniz. Uygun mu?

Okey no problem

**Comment by z0o0p** [comment]
@safak45x, your work was added to the codebase via PR #15. It will be seen in the next release. Thank you!

**Pull request closed without merging**
